### ISSUE TITLE
Change `All Assets` link to breadcrumbs in the Assets category page

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1004]
<img width="535" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFNTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a673422ea6f65547331f260e7426eed6894569c/image.png" alt="image.png" />

@ionuiux please paste the design here

**Comment by ionuiux** [comment]
Design mockup - https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=12345-119204&t=kSZ5uT0kDsPxsGkU-11
