### ISSUE TITLE
Add an indicator in the asset info about how recent the data is

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1017]
The icon should have a gradient color between gray (stale) and (green) active
The tooltip should have the following info:

```
First seen: 2 days ago
Last data: 1 min ago
```

@ionuiux to provide detailed design

**Comment by ionuiux** [comment]
Design mockup - https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=12468-95821&t=j86rAMqgly5Xtr4V-11
