### ISSUE TITLE
Digma early access program notification

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1031]
Notification should be shown for some users instead of the free course promotion (using the same infra)

Please see the IntellIJ story here:
https://app.zenhub.com/workspaces/digma-team-629081e5a37b4b0015ac6813/issues/gh/digma-ai/digma-intellij-plugin/2440

Mockups are here:
https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=12010-189963&t=r6h6QsERpvQo1prZ-11

**Comment by shaykeren** [comment]
@doppleware after user register via the 'early access' should we show again the 'free course promotion' ?

**Comment by doppleware** [comment]
Yes

**Comment by opoliarush** [comment]
Delay between promotions will be 1d
