### ISSUE TITLE
Heatmap - Drilldown to entry points from service

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1046]
See mockup 
https://www.figma.com/proto/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?page-id=13456%3A263745&node-id=13456-266377&viewport=253%2C-6467%2C1.02&t=cqX5WC7LZus7PPy9-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=13456%3A266377

<img width="1082" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d62aced8fd91acc26073374f30d1579f58c7357/image.png" alt="image.png" />

<img width="1081" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHZpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--284fd556966167e1ca8dd615b1ead86838e0ae2f/image.png" alt="image.png" />

Clicking on a service name should show a heatmap of all entry points as seen on the mockup.
In the transition we should keep following values from the previous page we came from:
1. Environment
2. Period
3. Changes/Baseline value
4. Tab type (Table/Heatmap)

If there are no entry points for that service under the selected environment then we need to have 'no entry points recorded for this environment'. @ionuiux could you please add?

Environment selector:
The user can choose to select a different environment from this page in the filter control. The list of selectable environments should be all environments the service was recorded under.

Filters:
For this story, include only the following components in the filters header:
* Environment selector
* Period (in the changes view)
* Toggle between heatmap/table visualization

**Comment by shaykeren** [comment]
related to backend #related to : https://github.com/digma-ai/digma-collector-backend/issues/2499

**Comment by ionuiux** [comment]
Design mockup - https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=13847-313012&t=FljumimqYyEkihbd-11

**Comment by shaykeren** [comment]
@kshmidt-digma for the environments list (Filter) please use this  new API https://github.com/digma-ai/digma-collector-backend/issues/2507 
This API returns environments for a specific service
