### ISSUE TITLE
Heatmap - Clicking on endpoint issues should open issues view for that endpoint

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1049]
<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGZpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6bc1b86f717b6c7204c3b95a5536dcb381d83f2/image.png" alt="image.png" />

When the user clicks on the endpoint issues link in the endpoint drilldown view for a service, it should change the scope in the main panel to that endpoint and open the issues tab. The selected environment should also be the environment currently selected in the heatmap document.

Data and Endpoints filters are  not part of this issue

In the table view you can see the issues link when you hover on the value of the issues count and impact value:

<img width="1048" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeURpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa27b773c536e085f227c74891738d8e4468e142/image.png" alt="image.png" />

**Comment by shaykeren** [comment]
related to : https://github.com/digma-ai/digma-collector-backend/issues/2499
