### ISSUE TITLE
Metrics Adjustments - Services Issues View - Styling Gaps

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#1053]
- [x] All the dropdown selectors should have the same width
![image](https://github.com/user-attachments/assets/3a476894-fa67-42a2-b1a6-f18081df52d6)

- [x] All the dropdown selectors should have the same min-width of 190px

- [x] Let's change service name and issues counter to new typography: Service name - Subheading 2/20 - Regular, issue count - Subheading 2/20 - Bold
![image](https://github.com/user-attachments/assets/e2f5832e-a33f-49a6-8ae8-a881f3b41f7e)

- [x] Reuse typographies

- [x] Check the color for "Endpoints" word in the report title

- [x] Check icons in the Empty state

- [ ] Trim cell content in Table

**Comment by kshmidt-digma** [comment]
@ionuiux 
Please add the mockup for the updated master components of Select and Toggle Swtich (with label or icon)

**Comment by kshmidt-digma** [comment]
Fixed in #1070
