### ISSUE TITLE
Choose data type for heat map(TBD)

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1056]
Provide option to include different criticality level issues based on user selection.
options should match criteria for critical medium and low

@doppleware what does it mean red/orange/blue

@shaykeren it means this:<img width="575" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd16ebb497ff4010d250411a5c06c63759fcba1b/image.png" alt="image.png" />

<img width="664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpuQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88388ccd9431cda27aed8a343749191a21d73c85/image.png" alt="image.png" />

**Comment by shaykeren** [comment]
when user selects criticality: Medium and clicks on the score link, what kind of filters should be applied on the issues tab in the main view?  right now the only filters applied are :
service click - home, environment, service 
endpoint click - endpoint scope, environment, service
we don't have a way to filter by criticality: medium
@doppleware

**Comment by doppleware** [comment]
@shaykeren No filter should be applied.He'llbe able to see al of the service/endpoint issues
