### ISSUE TITLE
Errors page implementation in the `Home` scope

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1075]
See mockup:
https://www.figma.com/proto/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?page-id=4193%3A89582&node-id=12929-173939&viewport=541%2C-60947%2C0.87&t=AbhBdFz2FRL2nqLq-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=12929%3A173939&show-proto-sidebar=1

Explanation of link behavior:
<img width="1162" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMElNQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--226f31d20df6520885567fba4cf58252effc72e1/image.png" alt="image.png" />

Step 1:
Show all errors in Home.
Use new styling. The status label (e.g `Escalating, High number of errors` is shown in today's implementation as `Characteristic`)

Features NOT included in step 1: 
* Filters
* Affected endpoints
* Ticket
* Dismiss
* Dates selection

Search should be by:
Message, Exception Type, Location (where the error was triggered)
Sort should be by criticality (score)/newest

<img width="545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWdDQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1d801e8b85b2badc04f12f8e1614e52620a6462/image.png" alt="image.png" />

Step 2: 
Add the `affected endpoint` to the error card (similar to issues).
This widget should be shown only if we know what the endpoints are based on the traces associated with the error.

Step 3: 
Add filter by services. Add the filter component (our standard one) and a services filter box. The errors shown are only those that were triggered by these services. (today we already have that connection between errors -> services). The list of services in the filter should be all services in the current environment. (not just those with errors).

Step 4: 
Add filter by affected endpoints. The endpoint list should be affected by the services filter and vice versa (like in Assets Filters today).  Endpoints are sorted by alphabet.  Endpoints are - HTTP, Consumer and Internal Operations

Step 5: 
Add date filter, the user should be able to see only errors that occurred on specific days (last x days)

Step 6: 
Add chart option for an error, this allows the user to see the number of occurrences on each day.

<img width="519" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejhNQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb65564e3481e3cfbe34005325fc321a7470a9da/image.png" alt="image.png" />

Step 7: 
Add pin option - this error will be pinned to the top (regardless of filters and always at the top). 
The user would like to follow a specific error. The pin is global for an env.

Step 8: 
Add a dismiss option,when the user is not interested in an error or he deemed it unimportant. These errors will move into a 'dimissed' status (similar to issues). The user will still have the option to `show` them again by clicking on the eye icon at the bottom (similar to issues).

**Comment by shaykeren** [comment]
epic created https://github.com/digma-ai/digma-ui/issues/1084
