### ISSUE TITLE
Disabled state for filters box - text background and foreground are the same

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1076]
<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmNDQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7b14ec70c9e205dc235f20a0befa3ab0deb2cc4/image.png" alt="image.png" />

STR: 
Go to assets filters
Select two service under `Services`
Select an endpoint belonging to one service under `Endpoints`
Open the services filter again - observe that the disabled line text is not visible

**Comment by kshmidt-digma** [comment]
@ionuiux 
Please add the mockup for the "selected and disabled" state

**Comment by ionuiux** [comment]
mockup for the row selector - https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=6637-72561&t=uLy8w7i3SA5PWKlV-11 Keep in mind that we don't need hover state for disabled row (selected or unselected)
