### ISSUE TITLE
Navigation doesn't work for error details

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#1082]
Go to the errors tab (with at least one error)
Click on the error and observe the error details view
Clicking on the back button should navigate the user to the errors tab

**Comment by kshmidt-digma** [comment]
This behavior implemented in https://github.com/digma-ai/digma-ui/pull/1008

- The "back" button in the History Navigation navigates the user to the last selected tab in the previous scope
- The "back" button in the Error details navigates the user to the Errors list

https://github.com/user-attachments/assets/804b2cff-1c47-4f30-847a-82499b50d71b

**Comment by shaykeren** [comment]
canceled, there should be different task for the navigation changes
