### ISSUE TITLE
Top issues sometimes appears empty, sometimes has wrong empty state

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1090]
1. Sometimes appears empty: 

<img width="489" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9RQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ceb7aa1cf18b889ab00af6330aa5e8c47cb2531e/image.png" alt="image.png" />

In this case we have the `slow endpoint` issue, which isn't represented here:

<img width="513" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHNRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--521b9148065b21471c8ccdb7ef6ab88d92be66fa/image.png" alt="image.png" />

Expected behavior - show empty state and not an empty title.

2. Current empty state is wrong - @ionuiux please revise. Title should be- 'No issues found'  and text should be  `No issues` , 'No issues found in this asset`. The icon should also not be an X but a positive icon.

 <img width="507" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f621230e03c30f86caf9c7ea55174a2f110d7794/image.png" alt="image.png" />

**Comment by ionuiux** [comment]
Design mockup - https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=5055-54603&node-type=frame&t=FjKTfhYL1pOlAv80-11
