### ISSUE TITLE
Errors Home Scope - Add filter by services

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#1099]
Add filter by services. Add the filter component (our standard one) and a services filter box. The errors shown are only those that were triggered by these services. 

The list of services in the filter should be all services in the current environment. (not just those with errors).
Filters API - POST:/errors/filter

<img width="1042" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFl6Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f10b1fc6038ccd6ec9e79e989651fd84908f288/image.png" alt="image.png" />

Figma:
https://www.figma.com/proto/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?page-id=4193%3A89582&node-id=12929-173939&viewport=541%2C-60947%2C0.87&t=AbhBdFz2FRL2nqLq-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=12929%3A173939&show-proto-sidebar=1

**Comment by shaykeren** [comment]
related to backend issue #https://github.com/digma-ai/digma-collector-backend/issues/2562

**Comment by ohrebeniuk** [comment]
POST /errors/filter
Request:
```
{
    "environment": "",
    "services": []
}
```
Response:
```
{
	endpoints: [{ displayName: "", "spanCodeObjectId": ""},..],
	criticality: [//TODO],
	unhandled:[//TODO]
}
```

POST /errorTypes/filter
Request:
```
{
	"environment": "",
	"endpoints": [{"spanCodeObjectId":""},..],
	"services" : ["service1",..]
}
```

Response:
```
{
	"errorTypes": [{},..]
}
```

```
onServicesChange ->
	POST("/endpoints/filter")
	POST("/errorTypes/filter")

onEndpointsChange ->
	POST("/errorTypes/filter")
```
