### ISSUE TITLE
Top usage insight with value less  than 0.01%  will be disaplyed as 0% 

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#1141]
should show a different indication rather than 0% 
text like 'Insignificant' or 'Almost Zero'

@ionuiux @doppleware , please provide the right text for that

<img width="1870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0YrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8cf8a723ca414720ee73573f16eb54a87063e40f/image.png" alt="image.png" />

**Comment by doppleware** [comment]
@ionuiux @kshmidt please use the following solution:
Should show the 'less than' mark with our minimum value. So: ` >0.01`
