### ISSUE TITLE
Errors dismiss + show flow leads to bad state

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#1145]
1. Take an error and dismiss it
2. Click on eye icon to see dismissed error
3. Click on "Show"
4. See an inaccurate empty state - "No errors" 
5. There is no "eye" icon to see all errors again

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUtIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de768f5b425561f3f4cf0f57f9408640a1145ac6/Screen%20Recording%202024-10-30%20at%208.33.27%E2%80%AFPM.mov)

Expected behavior:
1. Show correct empty state -> Once all dismissed errors are shown return to regular errors view

**Comment by doppleware** [comment]
This happens in the issues tab too and needs to be solved there as well

**Comment by kshmidt-digma** [comment]
@doppleware 
Currently, the "Go back" button is in the tab header instead of the "eye" icon.
<img width="717" alt="Screenshot 2024-11-04 at 18 08 58" src="https://github.com/user-attachments/assets/e78d3642-4e29-476d-bf97-30948d6687a2">

Should we keep it?
