### ISSUE TITLE
Enlarge the width of the select dropdown for the list of endpoints in the Digma Metrics report

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-ui#1170]
Issues: having the long names of endpoints makes it hard to see the search results
<img width="781" alt="image" src="https://github.com/user-attachments/assets/bbebf117-00a2-4358-b8c6-d4fbd4c1b803">

**Comment by ionuiux** [comment]
Let's make the width of the selector results dynamic. The maximum width should be based on the longest endpoint name.
