### ISSUE TITLE
Publishing digma-ui artifacts

### ISSUE THREAD

**Issue by asafchen-dig** [digma-ai/digma-ui#1182]
We want to change the way we deploy digma-ui in helm chart. digma-ui should have a pipeline of creating an incremented release that has artifacts. Those artifacts are doing to be downloaded before nginx pod is starting, and extracted to nginx folder, so the artifacts should be arrange the same way we want them in nginx.
Note that this nginx serves also the jaeger login page, so it needs to be published as well.

See https://github.com/digma-ai/helm-chart/issues/282

**Comment by kshmidt-digma** [comment]
Closed in #1189
