### ISSUE TITLE
Automatic Start of Digma Backend Using Docker

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#146]
[Update: Please see the following Figma: https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?type=design&node-id=3226%3A481312&mode=design&t=dXP4wYesk0uKHX6L-1]

As a part of the setup wizard, check if Docker and Docker Compose  (via docker_compose or Docker compose ) are installed locally and try to do an automatic installation if that is the case.

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/dbfd3baa-0f9a-45a9-ae84-c3abb3130600)![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/6c8f6ba0-0ad1-4229-92bc-e531cf6d1a21)

1. This should run the Docker Compose file locally
2. Include complete analytics about issues, what strategy was used etc.
3. Add an env variable for deployment type to ensure we know this  is autoinstalled 

If it is not possible to install automatically we should fallback to the current screens for manual installation

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/1267ec73-2eb6-4b38-8238-ac429bbfb922)

Otherwise, indicate success and move to the next stage:
![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/4ec2440f-01b2-421a-a68d-2dc6bcfd6e21)

**Comment by shaykeren** [comment]
https://github.com/digma-ai/digma-ui/issues/150
