### ISSUE TITLE
Add local environment flow

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#188]
Motivation: Allow users to understand how to add environments easily in Digma and encourage them to do so

1. Show a + button that will always appear after the last environment in the recent activity environment tabs
2. When clicking the + button, the user will be prompted to set the name of the environment (inline) after clicking 'enter' or losing focus, the new environment is created in the UI only in a 'pending' state. See UI.
3. In the details page for that environment, the user will see instruction on how to send data to that environment (the ENV variable to set)
4. When data arrives for that environment the Environment tab name will be shown regularly (not as pending) and the data will be shown as usual. The instructions will disappear.
5. The pending environment should persist in state.
6. Add option to delete pending environment (UI needed)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDQvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9a5fcf9f880b14a225fa7afb2561675e183bc544/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDgvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ae5281eaec9a6a28b2c3284f5e334df05c8baec0/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUEvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--29d5f3d0661d677508602f5e23bd20b455e04765/image.png)

**Comment by shalom938** [comment]
@doppleware @shaykeren @kshmidt-digma 

from plugin side when user clicks "Add to the active run config"

we can add the environment variable to the run config settings but that will change the user's settings and if its in source control will cause a checkout.

we can also do that:
persist a map with runConfigName -> environment
when user runs this run config add the environment variable.
we can persist this map between IDE restarts.
