### ISSUE TITLE
Filter assets list for specific services

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#294]
1. Show a filter box next to the project name
2. The filter should default to 'all services'
3. The user can select any number of services 
4. Based on his selection the assets in the assets list will udpate
5. It will be persisted per project
6. For now it won't affect the data (so if an asset is used by two services and i filtered to one I will still see that asset and its overall insights, even if some are relevant to the other service)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWJ5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--344acfa932b07f4a2b6f82aca35cfa12abab81d5/image.png)

See filter box behavior in this link (only in that link it is shown over the Recent Activity)
https://www.figma.com/file/9WRmS8uKjUIv45ldWun2pt/UI---Shared?type=design&node-id=2264-146162&mode=design&t=TrEVhqFAJJnpNVtJ-4

**Comment by shaykeren** [comment]
assets tab should be moved to the react app, for that use plugin branch : remove-assets-tab
services filter should be next to the tab
