### ISSUE TITLE
Service filter in assets page should also affect the dashboard

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#304]
1. Setting a service filter in the assets page  should also set the same filter in the dashboard
1. Add a UI indication in dashboard for active filters that will open the sidepanel on the assets page when clicked,

https://www.figma.com/file/M6H4wKYVWhrybJPGpxYxSx?node-id=463%3A13862&utm_source=notification&utm_medium=slack&utm_content=0348b58b19e37a593bf899615d7b6fa5&type=design#637361838

**Comment by kshmidt-digma** [comment]
Maybe we can open the same dropdown with selected services just in place when we click the "Filter" button in the Dashboard. It would not require the user to switch the context. @doppleware, what do you think?

**Comment by doppleware** [comment]
I'm good with that solution
