### ISSUE TITLE
Add Jira ticket dialog in UI for N+1 query

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-ui#318]
The option will be added for N+1 insight to create an issue in Jira.
The dialog will be populated with the issue info, as seen below:

1. Summary: N+1 Issue found - [Service Name] (can be multiple, if so comma separated) - [Criticality]
2. Description:
N+1 Query Detected
Query
Related code location
Affected endpoints:
[Ep2]
Repeats: [x]
info by digma.ai
3. Attachment - option to download the Trace
4. Please add analytics to:
    a. Clicking on the "Jira Ticket" action
    b. Clicking copy on any of the fields
    c. Clicking download on the trace 

![image](https://github.com/digma-ai/digma-ui/assets/119138536/1e215f48-ff15-47d8-afd8-89d2df5e4405)

**Comment by shaykeren** [comment]
Criticality Label - 
Criticality : {Criticality Value:}
Criticality Value:
field type: double
should be taken from insight (criticality)
if the value equals 0 should show N/A
otherwise:
0-0.3 - Low
0.3 - 0.7 - Medium
0.7-1.0 - High
