### ISSUE TITLE
High number of queries UI

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#338]
This is the mockup:

<img width="492" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK042QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c8ba02648292f11436361c331bd0920af6c888e/image.png" alt="image.png" />

Please use this template to implement:
<img width="389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0o2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dda3162ac27377e6263130a5a9bc400913c45309/image.png" alt="image.png" />

Tooltip for 'Typical' - Typical number of queries for endpoints in this service.

**Comment by arik-dig** [comment]
relates to backend issue https://github.com/digma-ai/digma-collector-backend/issues/1433

**Comment by arik-dig** [comment]
@doppleware I see you added few properties to the insight

1) `Median Time` - what should it be? we measure the queries count...
2) "% of entire time" - not sure I understand.
3) for both 1 and 2, do you have some formula in mind?

**Comment by doppleware** [comment]
1. Defined in the original ticket: 
 
<img width="409" alt="image" src="https://github.com/digma-ai/digma-ui/assets/93863/dd9b4f79-e7fe-41e6-844f-4c54a8bab981">

2. How much of the endpoint duration is the duration of the queries.
3.

**Comment by arik-dig** [comment]
@doppleware ,
1. the Median described in the ticket relates to median of **queries count** and **not** to duration
2. we have that number in the duration breakdown, can we take it from there? 
and if not so need to have some formula for it.
