### ISSUE TITLE
Notification of Jira new feature

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#350]
If:
1. User never got this notification
2. There is an N+1 or N+1 Endpoint, Bottleneck or Bottleneck Endpoint issue detected (in assets or pane navigated to)

Show the following emphasis UI:
https://www.figma.com/file/M6H4wKYVWhrybJPGpxYxSx?node-id=969%3A13859&utm_source=notification&utm_medium=slack&utm_content=ce345570939bb84ee371fdae69010227&type=design#654734306

**Comment by shaykeren** [comment]
@doppleware what should be the  "try it now" button behavior?
