### ISSUE TITLE
missing info icon for insight:Query Optimization Suggested

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#429]
related to #https://github.com/digma-ai/digma-ui/issues/389#workspaces/digma-team-629081e5a37b4b0015ac6813
missing info icon for insight:
Query Optimization Suggested

TBD @doppleware, please provide the description for it

**Comment by doppleware** [comment]
Updated in the notion and also here:
This query has been found to be especially slow compared to other queries of the same type running against the same DB. Consider optimizing this query or caching it.
