### ISSUE TITLE
Endpoint bottleneck insight

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#440]
<img width="714" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a85f82e49bad41825fd00d15ca7a440481735961/image.png" alt="image.png" />

<img width="462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzVFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce8fe2d34259c52b0fc75465bf5e5af405790988/image.png" alt="image.png" />

Please note:
1. The current design is a list of spans/assets, in the new design we'll have a single insight for each
2. The insight icon color represents the severity

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/Design-System-3.0?type=design&node-id=2068-14799&mode=design&t=orYiJkzSk02p5Vg6-11
