### ISSUE TITLE
Span bottleneck insight

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#441]
<img width="739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE5FQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45aa4f02270da9700437f357153ee076af03f63f/image.png" alt="image.png" />

<img width="456" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFJFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3725e67f959df106b3b204ecbd07c765f26b263/image.png" alt="image.png" />

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/Design-System-3.0?type=design&node-id=2068-17591&mode=design&t=orYiJkzSk02p5Vg6-11
