### ISSUE TITLE
High Number of Queries insight

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#442]
<img width="735" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8032ae741d72e6c3b3c219823f9d5336f5daa81f/image.png" alt="image.png" />

<img width="337" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFpFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ac9be6120813a1c5c104f60367989523ba85fea/image.png" alt="image.png" />

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/Design-System-3.0?type=design&node-id=2068-18783&mode=design&t=orYiJkzSk02p5Vg6-11
