### ISSUE TITLE
Query Optimization Suggested insight

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#443]
<img width="432" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHhFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3138ff6a0eec901b9a99a2423daceb882e59b42/image.png" alt="image.png" />

<img width="267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODFFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ade8af33fad20b81ddb41663329877b600bccd3/image.png" alt="image.png" />

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/Design-System-3.0?type=design&node-id=2068-19925&mode=design&t=orYiJkzSk02p5Vg6-11
