### ISSUE TITLE
Show errors for assets 

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#455]
Given there is an asset 'span`' that also has a method associated with it in one of two ways:
1. Directly saved in the backend as a `MethodCodeObjectId`
2. Discoverable by the plugin (similar to the 'target' icon)

And that method has error stack frames associated with it. 

When I navigate to that span in any way, including:
1. Through the assets tab
2. Using the code button
3. Using a lens
4. Using an insight link 

I should see in the errors tab all of the errors associated with the method associated with this span

implementation details
asset scope should contains the following details:  (just an example)
```
    span_code_object_id [optional] (more details can be found https://github.com/digma-ai/digma-ui/issues/454)
    method_code_object_id  [optional] 
    display_name
```

Any scope change in the UI should follow these steps:
```
call assets/display_info API to get asset display information
if the response contains method_code_object_id (related to the current asset)
    set the scope with both span_code_object_id and method_code_object_id
else
    try to discover the method_code_object_id for that span_code_object_id
    if method found:
         set the scope with both span_code_object_id and method_code_object_id found by the discovery
   else 
         set the scope with both span_code_object_id with no method_code_object_id
after the scope is changed all tabs should be refreshed according to the scope

**errortab**
if scope.method_code_object_id  is not null:
     fetch errors from the backend by using  scope.method_code_object_id
     if num of errors > 0:
        show errors + red icon in the errors tab
    else:
       no errors empty state
```

https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=2452-46463&mode=design&t=Z4NAQFTz8hrIgEEw-11 - red dot design link

**Comment by kshmidt-digma** [comment]
Completed in #432
