### ISSUE TITLE
New Navigation : Filtering - Issues

### ISSUE THREAD

**Issue by opoliarush** [digma-ai/digma-ui#507]
**Filter button**
- Issue type (multi select)

**Motivation:** 
The user would like to find out if we have issues of a particular type (for example, n+1) or see all types of issues we found (especially relevant when looking globally at all issues and there is a large number of them). 

**Issue Type**
The list should always display all issues sorted by enabled first, alphabet. The ones that don't exist in the current data are disabled.

**Relation to toggle buttons**
The shortcut toggle buttons we have today in 'home' for 'Critical' and "Unread' will reflect the data after applying the filters. For example: I have 0 critical N+1 issues and I selected N+1 for the `Insight Type` filter. After clicking apply, the `Critical` toggle button should be at 0 and disabled.

Filters should persist as the assets today

Having Scope Home With Filters (issueType1(Set), issueTyp2(Set),issueTyp3,issueTyp4 )
When the scope changed to span1 that has only issue of type issueType1
Then I should see the filters with issueType1(Set), issueTyp2,issueTyp3,issueTyp4

**Comment by ionuiux** [comment]
https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/⭐-Design-System-3.0?node-id=6637-68846&t=5qDSwQobnSGmy9Ee-11 - dewsign mockup
