### ISSUE TITLE
Multiple assets select in code button not working

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#508]
STR:
I used this code from Petclinic:
<img width="1287" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d12dc8e1c57614f679c2c96c61fbb498473cf0d1/image.png" alt="image.png" />

However when I click the code button there is never any dropdown, I just go to the first asset.

```
	@WithSpan
	private boolean ValidateOwnerUser(Owner owner) {

		Span span = otelTracer.spanBuilder("db_access_01").startSpan();

		var max = ThreadLocalRandom.current().nextInt(90, 110 + 1);
		try {
			for (int i = 0; i < max; i++) {
				ValidateOwner();
			}
		}
		finally {
			span.end();
		}
		return true;

	}
```

**Comment by shaykeren** [comment]
otelTracer is injected into the ctor, this  is not supported by the discovery right now

**Comment by shaykeren** [comment]
no a bug, 
otelTracer is injected into the ctor, this is not supported by the discovery right now

**Comment by doppleware** [comment]
ok
