### ISSUE TITLE
Fixes required in new insights

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#570]
- [x]  @ionuiux please update the design for the  "Low Usage" and "Slow Endpoint" it does not look good currently

- [x]  Decrease main values font size to 12 (already updated in design system)

<img width="438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b6d60247dd771bf3ce089a15d94a823a3946c36/image.png" alt="image.png" />

- [x]  Check toolbar button sizes @ionuiux ?
- [x]  The first button from the right should always be a primary (text and icon), in all insights
- [x]  Cards are too far apart, please make margin a little smaller

<img width="443" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXVpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bdb452cc62fc1fa71c6853a4a521ad562440477/image.png" alt="image.png" />

- [x] Fix the insights page background color, it is a bit brighter than the design in the mockup. @ionuiux  please provide details. 

- [x] Endpoint dropdown should open when clicking on an empty area, not just on the caret

<img width="439" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTZpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b19b7eae0c7980914e2a534e7f620a13775d875a/image.png" alt="image.png" />

- [x] Adjust [Jira ticket hint](https://www.figma.com/file/2kxQzKJFUAOUcHXvSZrMQy/Digma-Design-System-2.1?type=design&node-id=299-16866&mode=design&t=Flu2VIGYVcTujBZI-0) to the new design  @ionuiux 
<img width="772" alt="image" src="https://github.com/digma-ai/digma-ui/assets/119138536/41fc3a1a-9fb6-4e0d-8141-007244ee67fe">

**Comment by kshmidt-digma** [comment]
Related to #681
