### ISSUE TITLE
Ticket icon has wrong color in Primary button

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-ui#579]
![image](https://github.com/digma-ai/digma-ui/assets/119138536/be202d13-835d-4c03-b44e-5fc83c2fd684)

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=3836-73025&mode=design&t=R7P37JwAvEbGvTX7-11 - Design Link
