### ISSUE TITLE
Two different ways to render trace button in list

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#589]
<img width="454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnVuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa85d3a22d265d8ca6885d4981bf95306cde406f/image.png" alt="image.png" />

<img width="454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnluQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da7a17270cd970246236aeceda2b914cbe89385c/image.png" alt="image.png" />

@ionuiux please decide on the right way and forward to engineering.

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=3836-72760&mode=design&t=R7P37JwAvEbGvTX7-11 - Design Link
