### ISSUE TITLE
Duration looks bad when little info available

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#590]
<img width="459" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af4c0e25294889f231d9e8080ba2fd566934af14/image.png" alt="image.png" />

@ionuiux  please work on layout and perhaps we can enrich with a call to action text:
"Trigger more actions to see the full duration analysis"

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=3834-71078&mode=design&t=R7P37JwAvEbGvTX7-11 - Design Link
