### ISSUE TITLE
Fix top usage insight layout

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#607]
The arrow should be pointing to the right and each row could be compressed to be one above (basically we don't need an empty row for each arrow.

<img width="554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUt0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d0543194602643b316dd6a9b8f5684b2f4e346c/image.png" alt="image.png" />

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=3105-49199&mode=design&t=apkYMzM9ePC52x2L-11 - Design Link
