### ISSUE TITLE
Add refresh button to insights and assets panel

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#612]
<img width="385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkt1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29052e6d73d971ec19eeabd2bf6622cbac7e42b0/image.png" alt="image.png" />

**Comment by kshmidt-digma** [comment]
Closed in #626
