### ISSUE TITLE
Implement UI for dismiss insight

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#616]
The following insights should NOT have the dismiss as an option:
Duration, Duration breakdown, Code Nexus, Endpoint Breakdown

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=3685-100577&mode=design&t=apkYMzM9ePC52x2L-11 - Design Link
