### ISSUE TITLE
troubleshooting documentation changes

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#625]
<img width="496" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0N5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d60942f9601ab5e068144966ad791a03c5a2bb8/image.png" alt="image.png" />

@kyrylo only digma.environment.id should be documented !!
no need to mention digma.environment or digma.user.id settings 
 
digma.environment.id=[ENVIRONMENT_ID] 
@ionuiux @kshmidt 
we need to point the user from where to take the environment id (clicking on the environment hamburger menu ...) , also screenshot will help here

**Comment by shaykeren** [comment]
close this one when done - https://github.com/digma-ai/digma-intellij-plugin/issues/2081

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=6132-115942&mode=design&t=n7ONDTFaAq2Bxfs1-11 - Design Link
