### ISSUE TITLE
text needs to be changed  for Endpoint Hight Traffic

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#642]
probably need to be fixed also in  Endpoint Low Traffic

change the Duration column to Calls

<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGkrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3a828afcd3aa6952215351de4a2d85aea363da8/image.png" alt="image.png" />

**Comment by kshmidt-digma** [comment]
Closed as duplicate of #641
