### ISSUE TITLE
Don't show the "eye" icon for dismissed insights if no dismissed insights 

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#652]
<img width="465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLy9CQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--449db2b9cf7278682df741e759ef9f1ac49d9069/image.png" alt="image.png" />

**Comment by shaykeren** [comment]
see comment for more details - https://github.com/digma-ai/digma-collector-backend/issues/1819#issuecomment-1987243030

**Comment by kshmidt-digma** [comment]
Closed in #672
