### ISSUE TITLE
Arrow is not aligned/v. center with text

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#653]
<img width="521" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c706cd14578d41477e7b16b2a835edcbe4d0f42/image.png" alt="image.png" />

**Comment by kshmidt-digma** [comment]
@ionuiux Please update the mockup
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=3105%3A49199&mode=dev

**Comment by ionuiux** [comment]
Updated - https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=3105-49199&mode=design&t=nMRdqNQWFYCQzCDX-11
