### ISSUE TITLE
User should be able to add environment when deployment type of server is helm

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#660]
If deployment type is Helm, don't show "Learn more" button.
Instead provide a link to "Add Environment" with the same empty state we already implemented for that showing how to instrument the app.

DeploymentType: Helm

**Comment by kshmidt-digma** [comment]
The following flow has been enabled:
- The user clicks on the "Add button."
- Registers
- Checks the connection via the corresponding wizard
- Proceeds to the instruction screen
