### ISSUE TITLE
Span side of query optimization and chattyapiendpoint  insights wrong UI

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#711]
1. Support the new endpoint query optimization insight and chattyapiendpoint  (depends on [#1874](https://github.com/digma-ai/digma-collector-backend/issues/1874), [#1876](https://github.com/digma-ai/digma-collector-backend/issues/1876))

chattyApiendpoint insight the insight type will be changed from EndpointChattyApi ->EndpointChattyApiV2

query optimization endpoint the insight type will be changed from EndpointQueryOptimization ->EndpointQueryOptimizationV2

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=4193-93468&mode=design&t=nL4gImbjt4wTMQ3i-11 - Design Link
