### ISSUE TITLE
Highlights - Performance

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#717]
related: https://github.com/digma-ai/digma-collector-backend/issues/1860
Figma: https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=4193-107295&mode=design&t=2korvFduhzWMH4r7-0

For now no need to support histogram view in the UI side

Color explanation: Green if the duration is within 20% of the median/p95 duration for the same span classification (Up to Median +20%)
Red if the duration is above that

**Comment by ohrebeniuk** [comment]
BE request/response example:

Request:
`GET https://localhost:3051/highlights/performance?scopedSpanCodeObjectId=span:OpenTelemetry.Instrumentation.AspNetCore$_$HTTP GET user`

the list of the environments can be added to the request to filter by specific environment.

Response:
[highlights-performance-response.json](https://github.com/digma-ai/digma-collector-backend/files/14762025/highlights-performance-response.json)

JCEF request example without environments filter:
window.cefQuery({
	request: JSON.stringify({
		"action": "HIGHLIGHTS/GET_PERFORMANCE",
		"payload": {
        "query": {
			"scopedSpanCodeObjectId": "span:OpenTelemetry.Instrumentation.AspNetCore$_$HTTP GET user"
		}
        }
	})
})

JCEF request example with environments filter:
window.cefQuery({
	request: JSON.stringify({
		"action": "HIGHLIGHTS/GET_PERFORMANCE",
		"payload": {
        "query": {
			"scopedSpanCodeObjectId": "span:OpenTelemetry.Instrumentation.AspNetCore$_$HTTP GET user",
                    "environments": ["#DIGMA#TESTS#CODELENSTESTS-SHOW_RUNTIMEDATA_WHENMETHODINSIGHTSWITHOUTDECORATORS-2024/03/04-14:52:41[LOCAL-TESTS]", "#DIGMA#TESTS#SPANDURATIONINSIGHTTESTS-SANITY-2024/03/05-10:52:48[LOCAL-TESTS]"]
		}
        }
	})
})
