### ISSUE TITLE
Assets filter is not applied on switching tabs

### ISSUE THREAD

**Issue by ohrebeniuk** [digma-ai/digma-ui#731]
1. Go to assets tabs
2. Filter by insight type
3. Switch to issue
4. Switch back to Assets

Actual result: Filter is not applied and applies only after 10 seconds
Expected result: Assets filtered by insight type

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFFXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3e43d21ce553a5c8b817ea8a8f55fdfdc4defb0/Assets%20filter%20bug.mp4)

**Comment by kshmidt-digma** [comment]
Closed in #732
