### ISSUE TITLE
recent activity - environment empty state (how to set up your environment)

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#772]
motivation:
1. user should be able to see the "how to set up your environment view" at any moment so he will be able to check the id of the current environment for troubleshooting and for different application setups.
2. user should be able to add the current set up to different run configs

proposal:

Add  Setup menu item (First item) to the environment hamburger  
Clicking on it should open the "How to set you ..." view, user should be able to close it 

empty state changes for public environment
no need to show the digma.user.id attribute, digma.environment.id is enough  

<img width="259" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjVwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb91f2f18e90439e1ea0819c561a558cc0e1c5bb/image.png" alt="image.png" />

<img width="1337" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnRwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--354d778ffa7296f7f07c05d84f49cfc86a0047b0/image.png" alt="image.png" />

**Comment by shaykeren** [comment]
please close this one when done - https://github.com/digma-ai/digma-intellij-plugin/issues/2080

**Comment by ionuiux** [comment]
Design Link - https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=6124-108827&mode=design&t=n7ONDTFaAq2Bxfs1-11
