### ISSUE TITLE
Allow 'clear all' operation for environment observability panel

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#792]
Users would like to be able to start from a clean slate and reset the observability data.

Acceptance Criteria

Given I observe traces in the recent activity in env A and no new traces arrive
When I click 'clear data' 
Then I should not see any traces in the recent activity

Given I clicked on 'clear data' in env A and no traces arrive
When I change to env B and back to A
Then I should not see any traces in the recent activity for env A

Given I clicked on 'clear data' in env A and no traces arrive
When I restart my Idea
Then I should not see any traces in the recent activity for env A

Given I clear all data of env A
When I produce new traces
Then I should see new traces in the recent activity

Instead of the `delete` operation which will delete the environment and create a new environment identifier - provide another menu option  'clear data' which will keep the environment ID but simply clear from the UI all observability traces previous to the current date when the button was clicked.

**Comment by ionuiux** [comment]
https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/⭐-Design-System-3.0?node-id=8367-116895&t=z6LrtAVnzAp0p4qz-11 - Design mockup
