### ISSUE TITLE
Basic functionality - assets page

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-ui#8]
1. Show a list of the groups (classifications) of different assets with count
2. Drilldown into an individual asset group. For now, use server-side data only (don't use client discovered assets).
Don't implement the filter yet - that will come later. Implement sort by: performance, latest 
3. Each asset should have a link to its code object page (that also opens that code location, for now). 

https://www.figma.com/proto/MTZJH09SSbyJjrKkbXcd3L/UX---shared?node-id=375%3A103505&scaling=min-zoom&page-id=180%3A29370&starting-point-node-id=375%3A99851

**Comment by arik-dig** [comment]
link to [backend issue](https://github.com/digma-ai/digma-collector-backend/issues/593)
