### ISSUE TITLE
Highlights v2

### ISSUE THREAD

**Issue by ionuiux** [digma-ai/digma-ui#821]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/⭐-Design-System-3.0?type=design&node-id=5422-92811&mode=design&t=Mk41Dclylp8bldvX-11- Design mockup

This feature includes the following:
1. Carousel component for top issues, max of 2 issues per page (animation is not in this scope)
2. Increase the number of top issues to up to 4
related to https://github.com/digma-ai/digma-collector-backend/issues/2072
3. Add insight icon and color to top insights card  (color is based on max criticality)
4. Add icons to each card
4. Color the environment icon in the top insights card based on environment insight criticality
5. Replace unlock insights background

**Comment by shaykeren** [comment]
related #https://github.com/digma-ai/digma-collector-backend/issues/2072
