### ISSUE TITLE
React error tab

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#829]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=4193-103791&mode=design&t=gmTvUCAiuOPmhgMi-4

**Comment by kshmidt-digma** [comment]
Task scope updates:
1. Errors tab is not visible in the Home scope
2. Pagination in the error list view is outside of this task
3. Environment list will not be visible on the card
4. Affected services will not be visible on the card
5. Sceletons will not be visible Related https://github.com/digma-ai/digma-ui/pull/845
