### ISSUE TITLE
Add number of spans to recent activity

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#843]
Add a 'Spans' column to the recent activity with the number of spans in the latest trace

https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=12740-161603&t=DEMQpTiVJrhd4wP5-11

**Comment by opoliarush** [comment]
min back version 
[v0.3.118](https://github.com/digma-ai/digma-collector-backend/releases/tag/v0.3.118)
