### ISSUE TITLE
Show better instructions for unsupported configs

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#856]
<img width="808" alt="image" src="https://github.com/digma-ai/digma-ui/assets/93863/b6c12b39-55ee-4d31-bf2a-f7cd57329be9">

Currently, if the config is not supported we show a very short 'Error' message that doesn't give any information.

Required behavior:

1. If the run config is not supported disable the 'Add to run config' link. The tooltip should say 'Automatic run config modification is not supported for this configuration type".
2. The instructions should also include the ENV variables to include the agent:
JAVA_TOOL_OPTIONS=-javaagent:${env.TMPDIR}/temp-digma-otel-jars/opentelemetry-javaagent.jar

**Comment by ionuiux** [comment]
https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/⭐-Design-System-3.0?node-id=7694-114746&t=2NDU1npQJhizQlPo-11 - Design mockup

**Comment by doppleware** [comment]
I did some testing, here are a few issues:
When the active run config is Maven (currently not supported) the ‘Set active run config’ option is available but clicking on the button does nothing (and now no error is shown)
When selecting a local environment and a run config that is not supported from a different type (for example composite) don’t use the full agent path but instead use: ${env.TMPDIR}

**Comment by kshmidt-digma** [comment]
During the testing, it was found that the `TMPDIR` variable is not present in some operating systems (e.g., OpenSuse Linux distro) and cannot be resolved when it is passed as a part of the Environment variable value in JetBrains Run Configuration.

As it can lead to a broken user flow, it was agreed to keep the real path for now.
