### ISSUE TITLE
Jira hint popup triggers the additional scroll in side panel

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-ui#876]
https://github.com/digma-ai/digma-ui/assets/119138536/c5a705b3-73ec-4b8d-b255-ac16bcfb791c

**Comment by opoliarush** [comment]
Scrolling insight with Jira popup and when insight hides under navigation, popup is still showing

**Comment by opoliarush** [comment]
![image](https://github.com/digma-ai/digma-ui/assets/156646693/ab8b5615-f30f-44d8-af2e-37a9684b6aab)
