### ISSUE TITLE
Digma engine is not starting after uninstall and re-install

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#943]
STR:
uninstall the plugin
observe the current docker status:
<img width="915" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODhYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d070fffc4a424f311269ea90e73d7fb273f991ba/image.png" alt="image.png" />
install the plugin
observe no connection view
go to setup digma
and observe: 
<img width="569" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c094bc41a1684034000ccd4ee52b623150e13c3b/image.png" alt="image.png" />

**Comment by opoliarush** [comment]
Could not reproduce on version 2.0.377+242
