### ISSUE TITLE
wrong data shown in analytics view when changing between issues/analytic tabs

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#956]
see attached video 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEV1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0898c49e1770e69e5b91a94c40ba5b18def85f90/Screen%20Recording%202024-08-04%20at%201.03.25%20PM.mov)

**Comment by kshmidt-digma** [comment]
Duplicate of #946 
Closed in #952
