### ISSUE TITLE
Filter module improvements

### ISSUE THREAD

**Issue by ionuiux** [digma-ai/digma-ui#968]
Here's a list of improvements for the filter module:

1. Add a close icon.
2. Change the color from `surface/secondary` to `surface/brand-darkest`.
3. Increase the corner radius from 4px to 8px

Design mockup - https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=11252-150699&t=t0yg59Yalnk9uaCM-11

**Comment by doppleware** [comment]
@opoliarush  please complete the review with Ion and close if done
