### ISSUE TITLE
missing low usage icon on asset card

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#975]
<img width="1590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0JSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5ac0084830943afeb02b608282eed481dad00e3/image.png" alt="image.png" />

**Comment by kshmidt-digma** [comment]
Implemented according https://github.com/digma-ai/digma-ui/issues/397
